wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    code_path: code/CXR/main.py
    framework: fastai
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.6
    start_time: 1680745878.20533
    t:
      1:
      - 1
      - 4
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      - 80
      2:
      - 1
      - 4
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      - 80
      3:
      - 13
      - 16
      - 23
      4: 3.10.6
      5: 0.13.10
      8:
      - 5
base_root:
  desc: null
  value: /home/dongdong/Medical-Image-Analysis/CXR/xray_jpg/
csv_name:
  desc: null
  value: chest_dongdong.csv
epochs:
  desc: null
  value: 50
loss_func:
  desc: null
  value: BCE
lr:
  desc: null
  value: 0.001
model_name:
  desc: null
  value: coatnet_0_rw_224
num_classes:
  desc: null
  value: 7
pretrained:
  desc: null
  value: true
save_name:
  desc: null
  value: model.pth
weight_decay:
  desc: null
  value: 0
